services:
  - type: web
    name: birthday-tracker
    env: python
    buildCommand: ""
    startCommand: "python serve.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
